### ISSUE TITLE
Issues with Embassy Owners

### ISSUE THREAD

**Issue by jakkuh** [pop4959/LWCX#69]
**LWC Version (/lwc admin version):** Dev Build which backported the "locking other peoples town chests" fix to 1.12.2
**Server version (/version):** 1.12.2

**Short five word summary of issue:** 
Embassy owners unable to lock items

**Detailed description of problem:**

It works on 1.12.2 now as well as newer versions, however, if someone has an embassy plot in their town, and someone out of town claims the embassy (as the feature intends), they then cannot claim containers with LWCX.

So that's something that would be nice to fix in the future.

**If there was an error in console, put it here:**
```
<paste it here between the little tick marks>
```

**Comment by pop4959** [comment]
Can you test this on the latest version of LWC? I was not able to reproduce this problem.

**Comment by pop4959** [comment]
@jakkuh Still wasn't able to reproduce the problem myself, but I pushed a fix that should theoretically work (based on discussion had with LlmDl, who pointed out a flaw in the current logic). Please test on the latest release of LWC and Towny for 1.13+ and let me know if it is working as expected now.

**Comment by jakkuh** [comment]
Just tested it out with the latest dev build of LWC, and the newest towny on a 1.15.1 server and embassy owners still do not appear to be able to lock chests in their embassy.

Here's a video of it: https://drive.google.com/a/linusmediagroup.com/uc?id=1_gwwsqr6ji2Fl9EADkA23meWiweS1RaQ

LWCX Config: https://pastebin.com/821dGUwd

To make sure we are on the same page, the user I tested with does not reside in the town he's standing in, in the video, but the mayor of that town gave me an embassy plot that I claimed and I still cannot lock chests there. 

Add me on Discord (jake#0001) and I can show you the issue in game.

**Comment by pop4959** [comment]
As discussed on Discord. ~

I was able to replicate it now with your instructions fairly easily. Thanks for the details. Should be working on the latest development build. Please test and let me know if it's working as you expect it on your end.

**Comment by pop4959** [comment]
Closed as fixed
